# Generated by Django 5.0.3 on 2024-06-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0005_alter_commentspost_blog_alter_replypost_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replypost',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='web_blog.commentspost'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
