# Generated by Django 5.0.3 on 2024-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0006_alter_replypost_comments_alter_tags_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='tag_blogs', to='web_blog.tags'),
        ),
    ]
