# Generated by Django 5.0.3 on 2024-06-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0007_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_blogs', to='web_blog.tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
